#!/usr/bin/env python3
"""Generate a C file embedding the Bally Astrocade system ROM(s) into the
binaries.

Usage: embed-roms.py <out.c> [--roms <rom>...]

The Astrocade's on-board 8K ROM (the "astro.bin" Professional Arcade BIOS,
plus the Bally Computer System / Home Library Computer variants) is
copyrighted firmware with no freely-redistributable class -- exactly like
the Intellivision port's Mattel EXEC/GROM. So there is only one class
(--roms), and with WITH_ASTROCADE_ROMS=OFF the caller passes none at all:
the generated table is empty and the session's "Import System ROMs..." path
is the only way to provision them. See COMPLIANCE.md.

The generated file lives in the build tree only.
"""

import sys
from pathlib import Path

# Sizes are asserted so a truncated or wrong-variant image is a build error
# rather than a machine that half-boots. All three console BIOS variants are
# 8 KB (MAME astrohome.cpp ROM_LOAD 0x2000).
EXPECTED = {
    "astro": 8192,      # Bally Professional Arcade (astrocde)
    "ballyhlc": 8192,   # Bally Home Library Computer (astrocdl)
    "bioswhit": 8192,   # Bally Computer System / White (astrocdw)
}


def emit_array(out, ident: str, data: bytes) -> None:
    out.write(f"static const unsigned char {ident}[] = {{\n")
    for i in range(0, len(data), 16):
        row = ", ".join(f"0x{b:02x}" for b in data[i:i + 16])
        out.write(f"    {row},\n")
    out.write("};\n\n")


def main() -> int:
    args = sys.argv[1:]
    if not args:
        sys.exit(__doc__)

    out_path = Path(args[0])
    roms: list[Path] = []
    if len(args) > 1:
        if args[1] != "--roms":
            sys.exit(f"embed-roms.py: expected --roms, got {args[1]}")
        roms = [Path(a) for a in args[2:]]

    entries = []
    for path in roms:
        name = path.stem
        if name not in EXPECTED:
            sys.exit(f"embed-roms.py: unknown ROM {name} ({path})")
        data = path.read_bytes()
        if len(data) != EXPECTED[name]:
            sys.exit(f"embed-roms.py: {path} is {len(data)} bytes, "
                     f"expected {EXPECTED[name]}")
        entries.append((name, data))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8", newline="") as out:
        out.write("/* Generated by tools/roms/embed-roms.py -- do not edit.\n"
                  " *\n"
                  " * See COMPLIANCE.md before redistributing a binary built\n"
                  " * from this file with the Bally system ROMs in it.\n"
                  " */\n\n")
        out.write('#include "roms_embedded.h"\n\n')

        for name, data in entries:
            emit_array(out, f"rom_{name}", data)

        out.write("const astro_embedded_rom astro_embedded_roms[] = {\n")
        for name, data in entries:
            ident = f"rom_{name}"
            out.write(f'    {{ "{name}.bin", {ident}, sizeof {ident} }},\n')
        out.write("};\n\n")
        out.write(f"const int astro_embedded_rom_count = {len(entries)};\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
