#!/usr/bin/env python3
"""Generate a C file embedding the community SDL_GameControllerDB mapping
text into the binaries.

Usage: embed-gamecontrollerdb.py <out.c> <gamecontrollerdb.txt>

SDL3's own bundled controller mapping database can be missing entries for a
given controller (especially Bluetooth-connected pads, which often report
differently than they do over USB) depending on how recent the OS's packaged
libSDL3 is. This embeds the community-maintained, more frequently updated
mapping file from https://github.com/mdqinc/SDL_GameControllerDB (zlib
license, see third_party/gamecontrollerdb/LICENSE and COMPLIANCE.md) so every
target loads the same up-to-date mappings via
SDL_AddGamepadMappingsFromString(), regardless of what the OS ships.

The generated file lives in the build tree only.
"""

import sys
from pathlib import Path


def main() -> int:
    args = sys.argv[1:]
    if len(args) != 2:
        sys.exit(__doc__)

    out_path = Path(args[0])
    db_path = Path(args[1])
    data = db_path.read_bytes()

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8", newline="") as out:
        out.write(
            "/* Generated by tools/gamepad/embed-gamecontrollerdb.py -- do "
            "not edit.\n"
            " * Source: third_party/gamecontrollerdb/gamecontrollerdb.txt\n"
            " */\n\n"
            '#include "gamecontrollerdb_embedded.h"\n\n'
            "const char astro_gamecontrollerdb_text[] = {\n"
        )
        for i in range(0, len(data), 16):
            row = ", ".join(f"0x{b:02x}" for b in data[i:i + 16])
            out.write(f"    {row},\n")
        out.write("    0x00,\n};\n\n")
        out.write(
            f"const size_t astro_gamecontrollerdb_text_size = {len(data)};\n"
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
